# Generated by Django 5.0.6 on 2024-07-29 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='asientos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(370)]),
        ),
    ]
