# Generated by Django 5.0.6 on 2024-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0002_alter_avion_asientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
