# Generated by Django 5.0.6 on 2024-07-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0003_alter_mensaje_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
